version: '3.9'

services:
  database:
    image: postgres:15-alpine
    container_name: postgres_database
    environment:
      POSTGRES_USER: userTeam3
      POSTGRES_PASSWORD: passwordTeam3
      POSTGRES_DB: dbTeam3
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5430:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/pgdata
    restart: always
    networks:
      - app-network

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    restart: always
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - app-network


  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ../../frontend/build:/usr/share/nginx/html
      - ../nginx/nginx.conf:/etc/nginx/conf.d/default.conf

    depends_on:
      - backend
    restart: always
    networks:
      - app-network

  backend:
    build: ../../backend
    container_name: backend
    volumes:
      - ../../backend:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    restart: always
    networks:
      - app-network
    depends_on:
      - database


networks:
  app-network:
    driver: bridge  


volumes:
  pgdata:
