version: '3.9'

services:
  backend:
    build: ../../backend
    volumes:
      - ../../backend:/app
    environment:
      - DEBUG=1
      - DATABASE_URL=postgresql://team3:password-team3@database:5432/database-team3
    networks:
      - app-network
    depends_on:
      - database

  database:
    image: postgres:15-alpine
    container_name: database
    restart: always
    environment:
      POSTGRES_DB: database-team3
      POSTGRES_USER: team3
      POSTGRES_PASSWORD: password-team3
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    restart: always
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - app-network


  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./frontend/build:/usr/share/nginx/html
      - ../nginx/default.conf:/etc/nginx/default.conf
    depends_on:
      - backend
    networks:
      - app-network


networks:
  app-network:
    driver: bridge  


volumes:
  postgres_data: