version: '3.9'

services:
  backend:
    build: ../backend
    ports:
      - "8000:8000"
    volumes:
      - ../backend:/app
    environment:
      - DEBUG=1
    networks:
      - app-network

  frontend:
    build: ../frontend
    ports:
      - "3000:3000"
    volumes:
      - ../frontend:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - app-network

  database:
    image: postgres:latest
    container_name: database
    restart: always
    environment:
      POSTGRES_DB: database-team3
      POSTGRES_USER: team3
      POSTGRES_PASSWORD: password-team3
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    restart: always
    ports:
      - "1025:1025"
      - "8025:8025"


  # nginx:
  #   build: nginx:latest
  #   container_name: nginx
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ../nginx/nginx.conf:/etc/nginx/nginx.conf
  #   depends_on:
  #     - backend
  #     - frontend
  #   networks:
  #     - app-network


# networks:
#   app-networks:
#     driver: bridge  


volumes:
  database: