# Generated by Django 5.2.1 on 2025-05-29 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_image_book_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='availability',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='book',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='book',
            name='utc_code',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
