# Generated by Django 5.2.1 on 2025-05-29 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_availability_book_rating_book_utc_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='utc_code',
            new_name='upc_code',
        ),
    ]
