name: Deploy DevOps Folder

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Copy DevOps folder to server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{secrets.SSH_HOST}}
          username: ${{secrets.SSH_USER}}
          key: ${{secrets.SSH_PRIVATE_KEY}}
          source: "DevOps"
          target: "home/ubuntu"

      - name: SSH Deploy Command
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{secrets.SSH_USER}}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/DevOps
            docker-compose down
            docker-compose up -d --build
