name: Django CI

on:
  push:
   branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python_version: '3.13'

      - name: Install dependencies
        run: python -m pip install --upgrage pip
            pip install -r requirements.txt
        working-directory: backend
        
      - name: Run Tests
        run: python manage.py test
        working-directory: backend

      - name: Build project
        run: npm run build
        working-directory: backend